# CI environment
dist: bionic

jobs:
  include:
    - language: python
      python: "3.7.9"
      install:
        - cd backend
        - pip install -r requirements.txt
      script:
        - pylint **/*.py --load-plugins pylint